server:
  port: '8080'
  servlet:
    session:
      timeout: 4320m
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/simpletaskDB'
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  messages:
    basename: messages
  mvc:
    static-path-pattern: /static/**
